### ISSUE TITLE
Flask `MethodView` and `flask-smorest`

### ISSUE THREAD

**Issue by afraazali** [di/flask-accept#13]
I have code that looks like the following:

```
blp = Blueprint(
    "example", "example", url_prefix="/example"
)
@blp.route(
    "/test/<string1>/<string2>",
)
class Test(MethodView):
    @blp.arguments(...)
    @blp.response(...)
    @blp.paginate()
    @accept('application/vnd.your_vendor.v1', 'application/vnd.your_vendor.v2')
    def get(self, args, string1, string2, pagination_parameters):
        ...

    @get.support('application/vnd.your_vendor.v3')
    def get_v3(self, args, string1, string2, pagination_parameters):
        ...
```

I'm getting the following error when I try to hit either endpoint:

`AttributeError: 'function' object has no attribute 'support' // Werkzeug Debugger`

Is there support for Flask's `MethodView`?

**Comment by di** [comment]
Can you give me a more complete, minimally reproducing example? I tried this:

```python
from flask import Blueprint, Flask
from flask.views import MethodView
from flask_accept import accept

blp = Blueprint("example", "example", url_prefix="/example")


@blp.route("/test/<string1>/<string2>",)
class Test(MethodView):
    @blp.arguments(...)
    @blp.response(...)
    @blp.paginate(...)
    @accept("application/vnd.your_vendor.v1", "application/vnd.your_vendor.v2")
    def get(self, args, string1, string2, pagination_parameters):
        pass

    @get.support("application/vnd.your_vendor.v3")
    def get_v3(self, args, string1, string2, pagination_parameters):
        pass


app = Flask(__name__)
app.register_blueprint(blp)

app.run(debug=True)
```

But it gives me:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    class Test(MethodView):
  File "test.py", line 10, in Test
    @blp.arguments(...)
AttributeError: 'Blueprint' object has no attribute 'arguments'
```

Where does `blp.arguments`, `blp.response` and `blp.paginate` come from?

**Comment by afraazali** [comment]
Apologies, here's the sample application from flask-smorest's quickstart:

```
from flask import Flask
from flask.views import MethodView
import marshmallow as ma
from flask_smorest import Api, Blueprint, abort
from flask_accept import accept


app = Flask(__name__)
app.config['API_TITLE'] = 'My API'
app.config['API_VERSION'] = 'v1'
app.config['OPENAPI_VERSION'] = '3.0.2'
api = Api(app)


class PetSchema(ma.Schema):
    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()

class PetQueryArgsSchema(ma.Schema):
    name = ma.fields.String()

blp = Blueprint(
    'pets', 'pets', url_prefix='/pets',
    description='Operations on pets'
)

@blp.route('/')
class Pets(MethodView):

    @blp.arguments(PetQueryArgsSchema, location='query')
    @blp.response(PetSchema(many=True))
    @accept('application/vnd.your_vendor.v1')
    def get(self, args):
        """List pets"""
        return [{"id": 1, "name": "Version 1"}]

    @get.support('application/vnd.your_vendor.v2')
    def get_v2(self, args):
      """ List pets v2"""
      return [{"id": 2, "name": "version 2"}]

api.register_blueprint(blp)
```

Trying to run the app will produce the error mention above. Thank you.

**Comment by di** [comment]
It looks like `flask-smorest` is not correctly passing the original function through w/ new attributes.

Moving the `flask-accept` decorator to the outside should fix this:

```diff
 @blp.route("/")
 class Pets(MethodView):
+    @accept("application/vnd.your_vendor.v1")
     @blp.arguments(PetQueryArgsSchema, location="query")
     @blp.response(PetSchema(many=True))
-    @accept("application/vnd.your_vendor.v1")
     def get(self, args):
         """List pets"""
         return [{"id": 1, "name": "Version 1"}]
```

**Comment by afraazali** [comment]
Thank you @di! That worked.
