### ISSUE TITLE
Error generating Swagger with flask-restx 0.3.0

### ISSUE THREAD

**Issue by BugliL** [di/flask-accept#14]
With version `0.3.0` of `flask-restx` it's not working anymore (see Full Stacktrace for details), i downgraded to version `0.2.0` and it's working.
Do someone know how to solve this issue?
Is this project still manteined? ( i did not see commits in a while )

**Example Source code**
```python
@dummy_namespace.route('/ciao', doc={'description': 'funziona'})
class DummyEndpoint(Resource):
    @responds('DummyData', description='Api', schema=DummyReturnData, status_code=200, api=dummy_namespace)
    def get(self):
        return {
            'ciao': 'HELLO MOTO',
            'banana': 'mela',
            'valore': 12,
        }
```

 
**Full stacktrace**
```
 * Serving Flask app "application/webserver.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 947-995-830
127.0.0.1 - - [09/Apr/2021 12:09:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2021 12:09:52] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2021 12:09:52] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2021 12:09:52] "GET /swagger.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 651, in error_router
    return original_handler(f)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 649, in error_router
    return self.handle_error(e)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 651, in error_router
    return original_handler(f)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 649, in error_router
    return self.handle_error(e)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 392, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/api.py", line 415, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/buglil/Desktop/FlaskFrontoffice/venv/lib/python3.8/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

**Comment by di** [comment]
Hi, this is the tracker for https://pypi.org/project/flask_accept/. It doesn't seem like that issue is due to `flask-accept` or that you're even using this library in that example. Can you confirm?

**Comment by BugliL** [comment]
Sorry, my bad, i confused Tabs on my Firefox, 
I was opening an Issue for https://github.com/apryor6/flask_accepts
you can destroy my issue, it's not related at all.
Have a nice day
